name: Publish Nightly

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Grant write permission ONLY to this job to modify pyproject.toml
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Create dynamic nightly version
        run: |
          # Extract the base version from pyproject.toml (e.g., "0.5.0")
          BASE_VERSION=$(cat pyproject.toml | grep -oP 'version = "\K[^"]+')

          # Create a date-based suffix (e.g., ".dev20250719203543")
          NIGHTLY_SUFFIX=".dev$(date +'%Y%m%d%H%M%S')"

          # Combine them into the full nightly version (e.g., "0.5.0.dev20250719203543")
          NIGHTLY_VERSION="$BASE_VERSION$NIGHTLY_SUFFIX"

          echo "Setting package version to: $NIGHTLY_VERSION"

          # Update the version in pyproject.toml
          sed -i "s/version = \"$BASE_VERSION\"/version = \"$NIGHTLY_VERSION\"/" pyproject.toml
      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      # This permission is mandatory for trusted publishing to PyPI.
      id-token: write

    # Using a dedicated environment for PyPI is a recommended security practice.
    environment:
      name: nightly
      url: https://pypi.org/p/tensorcontainer

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/